# Generated by Django 3.2.9 on 2021-12-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='slug',
        ),
    ]
